version: "3.9"

services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    networks:
      - grpcNet
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8084:50051"
    networks:
      - grpcNet
  postgresdb:
    image: postgres:15.0
    container_name: loms-postgres
    hostname: postgres
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12341234
      - DATABASE_HOST=127.0.0.1
    ports:
      - "1235:5000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./loms/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - loms-pg-data:/var/lib/postgresql/data
    networks:
      - grpcNet
networks:
  grpcNet:
volumes:
  loms-pg-data: {}