// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package stocks_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StocksStock struct {
	ID         int64
	Sku        int32
	TotalCount int32
	Reserved   int32
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
