// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orders_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrdersItem struct {
	ID        int64
	OrderID   int64
	Sku       int32
	Count     int32
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type OrdersOrder struct {
	ID        int64
	UserID    int64
	Status    pgtype.Text
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
